kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ray-ml-notebook
  labels:
    opendatahub.io/notebook-image: 'true'
  annotations:
    opendatahub.io/notebook-image-name: "Ray ML Notebook"
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/ray-ml-notebook"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with ray dependencies set."
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.6"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"Ray","version": "1.12.1"}, {"name": "TensorFlow","version": "2.6.3"}, {"name": "Torch","version": "1.11.0"}]'
        openshift.io/imported-from: quay.io/thoth-station/s2i-ray-ml-notebook
      name: latest
      from:
        kind: DockerImage
        name: 'quay.io/thoth-station/s2i-ray-ml-notebook:v0.2.0'
      referencePolicy:
        type: Source
